title: Katherine McDonough
url: "https://kmcdono.com"
baseurl: "/"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: true
footer_url: "kmcdono.com"
footer_text: "Page design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/researcher/"
 - name: "CV"
   link: "cv_mcdonough_2024.pdf"

