title: Katherine McDonough
url: "https://kmcdono.com"
baseurl: "kmcdono.com"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "kmcdono.com"
footer_text: "Page design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "CV"
   link: "cv_mcdonough_2024.pdf"

